import { useEffect, useState } from "react";
import type { Activity } from "../api";
import { t } from "../i18n/store";

/**
 * Voices load asynchronously in some browsers (notably Chrome): a
 * getVoices() call right after page load can return [] even though voices
 * do exist. Wait for the "voiceschanged" event, but don't wait forever in
 * case the browser never fires it (or has no voices at all).
 */
function waitForVoices(): Promise<SpeechSynthesisVoice[]> {
  const existing = window.speechSynthesis.getVoices();
  if (existing.length > 0) return Promise.resolve(existing);
  return new Promise((resolve) => {
    const timer = setTimeout(() => resolve(window.speechSynthesis.getVoices()), 500);
    window.speechSynthesis.addEventListener(
      "voiceschanged",
      () => {
        clearTimeout(timer);
        resolve(window.speechSynthesis.getVoices());
      },
      { once: true },
    );
  });
}

/**
 * Plays an activity's real `podcast_url` audio when one was generated by the
 * backend TTS step. Falls back to the browser's built-in speech synthesis
 * (reading `desc` aloud) when there's no URL yet, or the audio fails to load
 * (e.g. the mock TTS provider's placeholder CDN URL) — so something is always
 * actually audible instead of just an animated progress bar.
 *
 * @param language ISO 639-1 code of the trip's dominant language (he/en/fr) —
 * used to pick a matching browser TTS voice for the fallback narration.
 * Defaults to Hebrew when the trip has none set, matching this app's
 * original (pre-i18n) behavior.
 */
export function usePodcastPlayer(language?: string | null) {
  const [playingPodcast, setPlayingPodcast] = useState<Activity | null>(null);
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!playingPodcast) {
      setProgress(0);
      return;
    }
    setProgress(0);
    setError(null);

    // Cleanup (e.g. React StrictMode's mount→cleanup→remount, or switching
    // straight from one podcast to another) cancels any in-flight speech/
    // audio. Browsers often fire that cancellation's "error"/"end" callback
    // synchronously, so without this guard the stale callback would call
    // setPlayingPodcast(null) right after the *next* podcast already started.
    let stopped = false;

    const speakAloud = (): (() => void) => {
      if (!window.speechSynthesis) {
        if (!stopped) setError(t("podcastPlayer.noTTS"));
        return () => {};
      }
      // Chrome silently drops a speak() issued in the same tick as a
      // preceding cancel() (exactly what happens above on remount/switch),
      // so cancel any leftover utterance and wait a tick before speaking.
      window.speechSynthesis.cancel();
      const narration = playingPodcast.podcast_brief
        ? `${playingPodcast.desc} ${playingPodcast.podcast_brief}`
        : playingPodcast.desc;
      const utterance = new SpeechSynthesisUtterance(narration);
      // Forcing an unsupported lang (e.g. "he-IL" with no matching voice
      // installed) makes speak() fail almost immediately on some browsers.
      // Only set lang to a voice that's actually available; otherwise leave
      // it unset so the browser uses its own default voice. Matched against
      // the *trip's* language (he/en/fr), not the UI language or a
      // hardcoded "he" — a French trip's podcast should be narrated in
      // French even if the app chrome is in Hebrew.
      let cancelled = false;
      const targetLang = (language || "he").toLowerCase();
      waitForVoices().then((voices) => {
        if (cancelled) return;
        const matchingVoice = voices.find((v) => v.lang.toLowerCase().startsWith(targetLang));
        if (matchingVoice) utterance.voice = matchingVoice;
        utterance.onend = () => {
          if (!stopped) setPlayingPodcast(null);
        };
        utterance.onerror = () => {
          if (!stopped) setError(t("podcastPlayer.ttsFailed"));
        };
        window.speechSynthesis.speak(utterance);
      });
      const estimatedMs = Math.max(2000, narration.length * 70);
      const start = Date.now();
      const interval = setInterval(() => {
        setProgress(Math.min(99, ((Date.now() - start) / estimatedMs) * 100));
      }, 200);
      return () => {
        cancelled = true;
        clearInterval(interval);
        window.speechSynthesis.cancel();
      };
    };

    if (!playingPodcast.podcast_url) {
      const cleanup = speakAloud();
      return () => {
        stopped = true;
        cleanup();
      };
    }

    const audio = new Audio(playingPodcast.podcast_url);
    let fallbackCleanup: (() => void) | undefined;
    const onTimeUpdate = () => {
      if (audio.duration) setProgress((audio.currentTime / audio.duration) * 100);
    };
    const onEnded = () => {
      if (!stopped) setPlayingPodcast(null);
    };
    const onError = () => {
      if (!stopped) fallbackCleanup = speakAloud();
    };
    audio.addEventListener("timeupdate", onTimeUpdate);
    audio.addEventListener("ended", onEnded);
    audio.addEventListener("error", onError);
    audio.play().catch(onError);

    return () => {
      stopped = true;
      audio.removeEventListener("timeupdate", onTimeUpdate);
      audio.removeEventListener("ended", onEnded);
      audio.removeEventListener("error", onError);
      audio.pause();
      fallbackCleanup?.();
    };
  }, [playingPodcast, language]);

  const togglePlay = (act: Activity) => {
    setPlayingPodcast((prev) => (prev?.id === act.id ? null : act));
  };

  const stop = () => setPlayingPodcast(null);

  return { playingPodcast, progress, error, togglePlay, stop };
}
