import { useEffect, useState } from "react";
import type { Activity } from "../api";

/**
 * Plays an activity's real `podcast_url` audio when one was generated by the
 * backend TTS step. Falls back to the browser's built-in speech synthesis
 * (reading `desc` aloud) when there's no URL yet, or the audio fails to load
 * (e.g. the mock TTS provider's placeholder CDN URL) — so something is always
 * actually audible instead of just an animated progress bar.
 */
export function usePodcastPlayer() {
  const [playingPodcast, setPlayingPodcast] = useState<Activity | null>(null);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    if (!playingPodcast) {
      setProgress(0);
      return;
    }
    setProgress(0);

    // Cleanup (e.g. React StrictMode's mount→cleanup→remount, or switching
    // straight from one podcast to another) cancels any in-flight speech/
    // audio. Browsers often fire that cancellation's "error"/"end" callback
    // synchronously, so without this guard the stale callback would call
    // setPlayingPodcast(null) right after the *next* podcast already started.
    let stopped = false;

    const speakAloud = (): (() => void) => {
      if (!window.speechSynthesis) {
        setPlayingPodcast(null);
        return () => {};
      }
      // Chrome silently drops a speak() issued in the same tick as a
      // preceding cancel() (exactly what happens above on remount/switch),
      // so cancel any leftover utterance and wait a tick before speaking.
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(playingPodcast.desc);
      utterance.lang = "he-IL";
      utterance.onend = () => {
        if (!stopped) setPlayingPodcast(null);
      };
      utterance.onerror = () => {
        if (!stopped) setPlayingPodcast(null);
      };
      const estimatedMs = Math.max(2000, playingPodcast.desc.length * 70);
      const start = Date.now();
      const interval = setInterval(() => {
        setProgress(Math.min(99, ((Date.now() - start) / estimatedMs) * 100));
      }, 200);
      const speakTimer = setTimeout(() => window.speechSynthesis.speak(utterance), 50);
      return () => {
        clearTimeout(speakTimer);
        clearInterval(interval);
        window.speechSynthesis.cancel();
      };
    };

    if (!playingPodcast.podcast_url) {
      const cleanup = speakAloud();
      return () => {
        stopped = true;
        cleanup();
      };
    }

    const audio = new Audio(playingPodcast.podcast_url);
    let fallbackCleanup: (() => void) | undefined;
    const onTimeUpdate = () => {
      if (audio.duration) setProgress((audio.currentTime / audio.duration) * 100);
    };
    const onEnded = () => {
      if (!stopped) setPlayingPodcast(null);
    };
    const onError = () => {
      if (!stopped) fallbackCleanup = speakAloud();
    };
    audio.addEventListener("timeupdate", onTimeUpdate);
    audio.addEventListener("ended", onEnded);
    audio.addEventListener("error", onError);
    audio.play().catch(onError);

    return () => {
      stopped = true;
      audio.removeEventListener("timeupdate", onTimeUpdate);
      audio.removeEventListener("ended", onEnded);
      audio.removeEventListener("error", onError);
      audio.pause();
      fallbackCleanup?.();
    };
  }, [playingPodcast]);

  const togglePlay = (act: Activity) => {
    setPlayingPodcast((prev) => (prev?.id === act.id ? null : act));
  };

  const stop = () => setPlayingPodcast(null);

  return { playingPodcast, progress, togglePlay, stop };
}
